author: Yours Truly
category: Education
description: |-
  You want to host your own [podcast](https://en.wikipedia.org/wiki/Podcast).
  You don''t need *anything* else.

  Boom.
email: yt@example.com
explicit: false
keywords:
- podcast
language: en-us
link: http://example.com
subtitle: A podcast on a single page.
title: One Page Podcast
